PUM/urls.py
# from django.conf.urls import include, url
# from django.contrib import admin
# from polls.views import Home,success,failure
# urlpatterns = [
#     # url(r'^admin/', include(admin.site.urls)),
#     url(r'^home/',Home),
#     url(r'^Success/',success),
#     url(r'^Failure/',failure),
#
# ]

from django.urls import path, include
from . import views
urlpatterns = [
    path('home/',views.Home,name="PUM.Home"),
    path('success/',views.success,name="PUM.success"),
    path('failure/',views.failure,name="PUM.failure"),
]

ulearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('',include("home.urls")),
    path('cpanel/',include("cpanel.urls")),
    path('blog/',include("blog.urls")),
    path('pgen/',include("pgen.urls")),
    path('course/',include("course.urls")),
    path('<str:country>/course/',include("course.urls")),
    path('training/',include("training.urls")),
    path('search/',include("search.urls")),
    path('events/',include("event.urls")),
    path('pum/',include("PUM.urls")),
    path('qna/',include("qna.urls")),
]

home/models.py
from random import choice
from django.db import models
from django.contrib.auth.models import AbstractUser
from helpers.basic import create_new_ref_number, create_ticket
from django.utils.text import slugify

# Create your models here.

class User(AbstractUser):
    phone = models.CharField(blank=True,max_length=15)
    profile_pic = models.ImageField(upload_to="static/profile",null=True)
    city = models.CharField(blank=False,max_length=30,default="")
    country = models.CharField(blank=False,max_length=30,default="")
    usertype = models.CharField(blank=False,max_length=200,default="user")
    def __str__(self):
        return self.username

class Course(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200)
    course_picture = models.ImageField(upload_to="static\\course")
    mark_popular = models.BooleanField(null=True)
    category = models.CharField(null=True,max_length=200)
    h1_name = models.CharField(null=True,max_length=200)
    description = models.TextField(null=True)
    key_features = models.TextField(null=True)
    what_you_learn = models.TextField(null=True)
    course_syllabus = models.TextField(null=True)
    meta_title = models.TextField(null=True)
    meta_description = models.TextField(null=True)
    meta_keywords = models.TextField(null=True)
    user = models.ManyToManyField(User, through="Enrollment")
    fee = models.IntegerField(null=True)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return f'/course/{self.slug}'

class Enrollment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    date_enrolled = models.DateField()
    final_grade = models.CharField(max_length=1,blank=True,null=True)
    status = models.CharField(null=True,max_length=200)
    txnid = models.CharField(null=True,max_length=200)
    amount = models.IntegerField(null=True)
    class Meta:
        unique_together = ['user','course']


class Training(models.Model):
    selecting_category = models.CharField(max_length=200)
    course_type = models.CharField(max_length=200)
    course_name = models.TextField()
    slug = models.CharField(max_length=200)
    h1_name = models.CharField(max_length=200)
    course_description = models.TextField()
    course_key_features = models.TextField()
    what_you_learn = models.TextField()
    course_syllabus = models.TextField()
    meta_title = models.TextField()
    meta_description = models.TextField()
    meta_keywords = models.TextField()
    course_picture = models.TextField()
    mark_popular = models.BooleanField(null=True)
    user = models.ManyToManyField(User,through="TrainingEnrollment")
    fee = models.IntegerField(null=True)

    def __str__(self):
        return self.course_name

class TrainingEnrollment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    training = models.ForeignKey(Training,on_delete=models.CASCADE)
    date_enrolled = models.DateField()
    status = models.CharField(null=True,max_length=200)
    txnid = models.CharField(null=True,max_length=200)
    amount = models.IntegerField(null=True)
    class Meta:
        unique_together = ['user','training']


class WithCountry(models.Model):
    countries = [
        ('inr', "India"),
        ('usd', "USD")
    ]
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    description = models.TextField(null=True)
    features = models.TextField(null=True)
    learn = models.TextField(null=True)
    syllabus = models.TextField(null=True)
    country = models.TextField(null=True)
    course_code = models.TextField( default=create_new_ref_number)
    scheduled_dates = models.TextField(null=True)
    scheduled_times = models.TextField(null=True)
    course_language = models.TextField(max_length=15, null=True)
    currency = models.CharField(max_length=20, choices=countries, default='inr')
    course_amount = models.IntegerField(null=True)

class WithCity(models.Model):
    countries = [
        ('inr',"India"),
        ('usd',"USD")
    ]
    description = models.TextField(null=True)
    features = models.TextField(null=True)
    learn = models.TextField(null=True)
    syllabus = models.TextField(null=True)
    country = models.TextField(max_length=30,null=True)
    city = models.TextField(null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    course_code = models.TextField( default=create_new_ref_number)
    scheduled_dates = models.TextField(null=True)
    scheduled_times = models.TextField(null=True)
    course_language = models.TextField(max_length=15,null=True)
    currency = models.CharField(max_length=20, choices=countries, default='inr')
    course_amount = models.IntegerField(null=True)


class WithOutCountryCity(models.Model):
    countries = [
        ('inr', "India"),
        ('usd', "USD")
    ]
    description = models.TextField(null=True)
    features = models.TextField(null=True)
    learn = models.TextField(null=True)
    syllabus = models.TextField(null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    course_code = models.TextField( default=create_new_ref_number)
    scheduled_dates = models.TextField(null=True)
    scheduled_times = models.TextField(null=True)
    course_language = models.TextField(max_length=15, null=True)
    currency = models.CharField(max_length=20, choices=countries, default='inr')
    course_amount = models.IntegerField(null=True)


class CourseTitle(models.Model):
    course_categories = [
        ("Project Management","Project management"),
        ("Agile & Scrum","Agile & Scrum"),
        ("IT Service Management","IT Service Management"),
        ("Quality Management","Quality Management")
    ]
    title = models.TextField(null=True)
    slug = models.TextField(null=True)
    category = models.CharField(max_length=30, choices=course_categories, default='Project Management')


class EnrollmentWithCountry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    with_country = models.ForeignKey(WithCountry, on_delete=models.CASCADE)
    date_enrolled = models.DateField()
    status = models.CharField(null=True, max_length=200)
    txnid = models.CharField(null=True, max_length=200)
    amount = models.IntegerField(null=True)

    class Meta:
        unique_together = ['user', 'with_country']


class EnrollmentWithCity(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    with_city = models.ForeignKey(WithCity, on_delete=models.CASCADE)
    date_enrolled = models.DateField()
    status = models.CharField(null=True, max_length=200)
    txnid = models.CharField(null=True, max_length=200)
    amount = models.IntegerField(null=True)

    class Meta:
        unique_together = ['user', 'with_city']


class EnrollmentWithOut(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    with_out = models.ForeignKey(WithOutCountryCity, on_delete=models.CASCADE)
    date_enrolled = models.DateField()
    status = models.CharField(null=True, max_length=200)
    txnid = models.CharField(null=True, max_length=200)
    amount = models.IntegerField(null=True)

    class Meta:
        unique_together = ['user', 'with_out']

class ErrorLog(models.Model):
    error = models.TextField(null=True)
    ts = models.DateTimeField()
    ticket_number = models.TextField(default=create_ticket)

class CountryList(models.Model):
    country_code = models.CharField(null=True, max_length=50)
    country_name = models.CharField(null=True, max_length=50)
    currency = models.CharField(null=True, max_length=50)
    region = models.CharField(null=True, max_length=50)

    def get_absolute_url(self):
        return f'course/{self.country_name}'


class CityList(models.Model):
    city_name = models.CharField(null=True,max_length=50)
    country_code = models.CharField(null=True,max_length=10)

class Faq(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    question = models.TextField(null=True)
    answer = models.TextField(null=True)

class Snippet(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(blank=True, null=True)
    body = models.TextField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args,**kwargs)
    def get_absolute_url(self):
        return f'/{self.slug}'

templates/cpanel_view/with/add-course.html
{% extends 'cpanel.html' %}
{% block css %}
<style>
  .errorlist > li {
    color: red;
  }
  .form-group > label{
    font-weight: bolder;
  }
  .fstElement {
    display: block !important;
  }
  .fstResultItem {
    font-size: 14px !important;
  }
  .fstMultipleMode .fstQueryInput {
    font-size: 14px !important;
  }
  .fstChoiceItem {
    font-size: 14px !important;
  }
</style>
{% endblock %}

{% block content %}
{% load poll_extras %}

{% for msg in messages %}
{{msg}}
{% endfor %}
{% if request.GET.with == "country" %}
<h4>Add course with country</h4>
{% elif request.GET.with == "city" %}
<h4>Add course with city</h4>
{% else %}
<h4>Add course without city/country</h4>
{% endif %}
<div class="basic-form">
  <form action="" method="post" novalidate >
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
      {{ field.label_tag }}
      {{ field }}
      {{ field.errors }}
      {% if field.help_text %}
      <p class="help">{{ field.help_text|safe }}</p>
      {% endif %}
    </div>
    {% endfor %}
    <div class="form-group">
      <input type="submit" class="btn btn-info" value="Add">
    </div>
  </form>
</div>

{% endblock %}

{% block script %}
<script type="text/javascript">
  $(document).ready(function () {
    if(window.location.search.includes('city')){
      $("#main-wrapper > div.content-body > div.container-fluid > div > div > div > div > div > form > div:nth-child(6) > label").html("Excluding Countries");
      $("#main-wrapper > div.content-body > div.container-fluid > div > div > div > div > div > form > div:nth-child(7) > label").html("Excluding Cities");
    }
    else if(window.location.search.includes('without')){
      console.log("....");
    }else{
      $("#main-wrapper > div.content-body > div.container-fluid > div > div > div > div > div > form > div:nth-child(7) > label").html("Excluding Countries");
    }
    $('.summernote').summernote();
    $("#id_country").append(new Option("Select Country",""))
    $.get("{% url 'CountryDetails' %}?q=c", function(data, status){
      for (let i = 0; i < data.length; i++) {
        $("#id_country").append(new Option(data[i][1],data[i][0]))
      }
    });
    $("#id_country").change(function(){
      $("#id_city").append(new Option("Fetching City list....",""))
      $.get("{% url 'CountryDetails' %}?c="+$("#id_country").val(), function(data, status){
        console.log(data)
        $("#id_city").find('option')
        .remove()
        .end();
        for (let i = 0; i < data.length; i++) {
          $("#id_city").append(new Option(data[i][0],data[i][0]))
          // console.log(data[i][0])
        }
      });
    })
  });

</script>
<script>
  $(document).ready(function(){
    $('.multipleSelect').fastselect();
  });
</script>
{% endblock %}

templates/cpanel_view/with/edit-with.html
{% extends 'cpanel.html' %}
{% block css %}
<style>
.errorlist > li {
    color: red;
}
.form-group > label{
    font-weight: bolder;
}
.fstElement {
    display: block !important;
}
.fstResultItem {
  font-size: 14px !important;
}
.fstMultipleMode .fstQueryInput {
    font-size: 14px !important;
}
.fstChoiceItem {
  font-size: 14px !important;
}
</style>
{% endblock %}

{% block content %}
{% load poll_extras %}

{% for msg in messages %}
{{msg}}
{% endfor %}
{% if request.GET.with == "country" %}
    <h4>Add course with country</h4>
{% elif request.GET.with == "city" %}
    <h4>Add course with city</h4>
{% else %}
    <h4>Add course without city/country</h4>
{% endif %}
<div class="basic-form">
    <form action="" method="post" novalidate >
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        {% if 'clone' in request.get_full_path %}
        <div class="form-group">
            <input type="submit" class="btn btn-info" value="Add">
        </div>
        {% else %}
        <div class="form-group">
            <input type="submit" class="btn btn-info" value="Update">
        </div>
        {% endif %}
    </form>
</div>

{% endblock %}

{% block script %}
<script type="text/javascript">
    $(document).ready(function () {
      if(window.location.search.includes('city')){
        console.log("..");
      }
      else if(!window.location.search.includes('city') && !window.location.search.includes('country')){
        console.log("....");
      }else{
        $("#main-wrapper > div.content-body > div.container-fluid > div > div > div > div > div > form > div:nth-child(7) > label").html("Excluding Countries");
      }
      $('.summernote').summernote();
    });

</script>
<script>

</script>
{% endblock %}